<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PageSeo;

class PageSeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
            [
                'page_name' => 'home',
                'page_title' => 'Best IVF Center in Srinagar | Fertility Specialist | India IVF',
                'meta_description' => 'Book consultation with India IVF Srinagar – 75%+ success rate, advanced fertility treatments, experienced doctors.',
                'meta_keywords' => 'IVF, fertility treatment, Srinagar, India IVF, infertility, fertility specialist, IVF center',
                'focus_keyword' => 'IVF center Srinagar',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'Best IVF Center in Srinagar | India IVF',
                'og_description' => 'Advanced fertility treatments and IVF procedures at India IVF Srinagar. High success rates with experienced specialists.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'Best IVF Center in Srinagar | India IVF',
                'twitter_description' => 'Advanced fertility treatments and IVF procedures at India IVF Srinagar.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'services',
                'page_title' => 'IVF Services & Treatments | Best Fertility Center in Srinagar | India IVF',
                'meta_description' => 'Comprehensive IVF services and fertility treatments at India IVF Srinagar. IVF, IUI, ICSI, and more advanced reproductive technologies.',
                'meta_keywords' => 'IVF services, fertility treatments, IUI, ICSI, reproductive technology, Srinagar',
                'focus_keyword' => 'IVF services Srinagar',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'IVF Services & Treatments | India IVF Srinagar',
                'og_description' => 'Comprehensive fertility services including IVF, IUI, ICSI and advanced reproductive technologies.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'IVF Services & Treatments | India IVF',
                'twitter_description' => 'Comprehensive fertility services including IVF, IUI, ICSI and advanced reproductive technologies.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'treatments',
                'page_title' => 'IVF Treatments & Procedures | Advanced Fertility Care | India IVF',
                'meta_description' => 'Comprehensive IVF treatments and fertility procedures at India IVF Srinagar. Advanced reproductive technologies and personalized care.',
                'meta_keywords' => 'IVF treatments, fertility procedures, reproductive technology, IVF procedures, Srinagar',
                'focus_keyword' => 'IVF treatments',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'IVF Treatments & Procedures | India IVF',
                'og_description' => 'Advanced fertility treatments and procedures with personalized care and high success rates.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'IVF Treatments & Procedures | India IVF',
                'twitter_description' => 'Advanced fertility treatments and procedures with personalized care.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'centres',
                'page_title' => 'Our IVF Centres & Locations | India IVF Network',
                'meta_description' => 'Find India IVF centres across multiple locations. State-of-the-art facilities and expert fertility care near you.',
                'meta_keywords' => 'IVF centres, fertility clinics, IVF locations, India IVF network, fertility centers',
                'focus_keyword' => 'IVF centres',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'Our IVF Centres & Locations | India IVF',
                'og_description' => 'Find India IVF centres across multiple locations with state-of-the-art facilities.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'Our IVF Centres & Locations | India IVF',
                'twitter_description' => 'Find India IVF centres across multiple locations.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'training',
                'page_title' => 'IVF Training & Education Programs | Fertility Specialist Training | India IVF',
                'meta_description' => 'Professional IVF training and fertility education programs at India IVF. Learn from experienced specialists and advance your career.',
                'meta_keywords' => 'IVF training, fertility education, reproductive medicine training, IVF courses, medical training',
                'focus_keyword' => 'IVF training',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'IVF Training & Education Programs | India IVF',
                'og_description' => 'Professional IVF training and fertility education programs with experienced specialists.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'IVF Training & Education Programs | India IVF',
                'twitter_description' => 'Professional IVF training and fertility education programs.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'about',
                'page_title' => 'About Us | Best IVF Center in Srinagar | India IVF',
                'meta_description' => 'Learn about India IVF Srinagar - our mission, experienced team, and commitment to helping couples achieve their dream of parenthood.',
                'meta_keywords' => 'about IVF center, fertility clinic Srinagar, IVF specialists, India IVF team',
                'focus_keyword' => 'about IVF center',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'About Us | India IVF Srinagar',
                'og_description' => 'Learn about India IVF Srinagar - our mission, experienced team, and commitment to helping couples.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'About Us | India IVF',
                'twitter_description' => 'Learn about India IVF Srinagar - our mission and experienced team.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
            [
                'page_name' => 'more',
                'page_title' => 'Additional Resources & Information | India IVF',
                'meta_description' => 'Explore additional resources, articles, and information about fertility treatments and reproductive health at India IVF.',
                'meta_keywords' => 'fertility resources, reproductive health information, IVF resources, fertility articles',
                'focus_keyword' => 'fertility resources',
                'canonical_url' => null,
                'index_follow' => true,
                'og_title' => 'Additional Resources & Information | India IVF',
                'og_description' => 'Explore additional resources, articles, and information about fertility treatments.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_title' => 'Additional Resources & Information | India IVF',
                'twitter_description' => 'Explore additional resources and information about fertility treatments.',
                'twitter_image' => null,
                'twitter_card' => 'summary_large_image',
                'twitter_site' => '@indiaivf',
                'twitter_creator' => '@indiaivf',
                'author' => 'India IVF',
                'robots' => 'index, follow',
                'is_active' => true,
            ],
        ];

        foreach ($pages as $page) {
            PageSeo::updateOrCreate(
                ['page_name' => $page['page_name']],
                $page
            );
        }
    }
} 